### ISSUE TITLE
Translation issue with message Wikimedia:Feverfew-ui.result.redirectTitle/fr

### ISSUE THREAD

**Issue by Mahabarata** [plantaest/feverfew#4]
Hi,

I would like to translate this on translatewiki.net
{redirectNumber, plural, =1 {1 redirect} other {# redirects}}

But I don't undestand what are the variables (not to be translated) and the texts (to translate).

**Comment by plantaest** [comment]
@

**Comment by plantaest** [comment]
Hi @Mahabarata,

This is the plural syntax in ICU Format. You can read more about this in below sources:
* https://formatjs.github.io/docs/core-concepts/icu-syntax/#plural-format
* https://crowdin.com/blog/2022/04/13/icu-guide#plural
* https://simplelocalize.io/blog/posts/what-is-icu/#plurals

The variable is `redirectNumber`. The texts are `1 redirect` and `# redirects`.

Regards, Plantaest.

**Comment by Mahabarata** [comment]
Ok, thanks : I translated the texts
